### PR TITLE
(INFRA-2909) Add windowsservercore-1909

### PR DESCRIPTION
**Pull request by yachub**
Hello, I opened [INFRA-2909](https://issues.jenkins.io/browse/INFRA-2909) as a request to add 1909 docker images. I simply added `hotspot-official.config` file and ran `./update-all.sh`. I'm not sure about the Jenkinsfile changes. Is this something you would consider adding support for until the upstream project merges/fixes https://github.com/AdoptOpenJDK/openjdk-docker/pull/365 ?

### CODE REVIEW

**Comment by olblak** [comment]
Hi @yachub , while we would be happy to build and publish the windowservercore-1909 image as we have everything in place for that, we are more concerned by long term maintenance and having a dedicated maintainer.

One of the things we recently discussed is to have CODEOWNERS for docker images as well, so you would be notified for pull request related to this windowsservercore-1909.

@MarkEWaite  @garethjevans  @slide

**Comment by olblak** [comment]
I had a discussion with @garethjevans about this pull request and he raised a valid concern. In order to build a docker image for a specific windows version, we need access to that system version. We use Packer to build images for the windows Lts version for our [Azure](https://github.com/jenkins-infra/packer-images/blob/master/azure/windows-2019-agent.amd64.json) and [Aws](https://github.com/jenkins-infra/packer-images/blob/master/aws/windows-2019-agent.amd64.json) environment. This is the reason why we only build the Lts version.

**Comment by slide** [comment]
I don't think we want to be in the "business" of supporting these images as general purpose images. We use them for publishing Jenkins docker images, but I don't think we want to support general usage anyway.

**Comment by olblak** [comment]
I'll bring this topic to the Jenkins infrastructure meeting tomorrow but considering that we already provide a Lts version, I don't think that the added value is enough considering the strong requirements it puts on infrastructure.

**Comment by MarkEWaite** [comment]
> I'll bring this topic to the Jenkins infrastructure meeting tomorrow but considering that we already provide a Lts version, I don't think that the added value is enough considering the strong requirements it puts on infrastructure.

I agree.  I don't think we should provide a 1909 Windows server image.

**Comment by olblak** [comment]
@yachub Thanks for the pull request but considering that we already build the lts version, building for this specific version put extra pressure on the ci environment and doesn't bring enough value so we decided to not build this specific version.

**Pull request closed without merging**
